gui:
  theme:
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - "#333333" # set to `default` to have no background colour
      - bold
    selectedRangeBgColor:
      - "#2B2D42"
      - bold
    cherryPickedCommitBgColor:
      - cyan
      - bold
    cherryPickedCommitFgColor:
      - blue
      - bold
    unstagedChangesColor:
      - red
      - bold
    defaultFgColor:
      - white

  showFileTree: true # for rendering changes files in a tree format
  showListFooter: false # for seeing the '5 of 20' message in list panels
  showRandomTip: false
  showBottomLine: false # for hiding the bottom information line (unless it has important information to tell you)
  showCommandLog: true
  showIcons: true

disableStartupPopups: true
notARepository: "prompt" # one of: 'prompt' | 'create' | 'skip'
os:
  editPreset: "nvim"
